### ISSUE TITLE
Horizontal scrolling on desktop and odd display on mobile.

### ISSUE THREAD

**Issue by cldershem** [indyhackers/indyhackers.org#150]
The new design has a little bit of a display issue that apparently drives me nuts enough to spend a few hours this afternoon documenting a fix. I'm not a front end person so this probably would have taken 10 minutes for someone else to get had I just reported the issue, but alas, I was determined! Unfortunately, I am also not a Ruby person, so I can't build the application, let alone figure out what files to change where to submit a proper PR. I pinged @mileszs and he suggested I open an issue documenting the required changes and someone who is more ruby-ficient can do the alchemy required to fix it in production.

The issue can be shown in a few screenshots:

- Desktop horizontal scrolling:
<img src="https://user-images.githubusercontent.com/201608/137820785-8db815ad-3c7f-4f91-aed9-8eab9051508f.png" width=500>
- Mobile right side padding:
<img src="https://user-images.githubusercontent.com/201608/137820956-f89df9ff-f6f4-42f9-825f-e69ffa8cba35.png" width=500>
- Mobile footer:
<img src="https://user-images.githubusercontent.com/201608/137821043-8a7861de-00a5-439b-90b4-6194adc164aa.png" width=500>

After the fix you get:
- mobile home page:
<img src="https://user-images.githubusercontent.com/201608/137821184-5d28a14c-ce27-48d9-a747-d1e6b88333cd.png" width=500>
- mobile footer:
<img src="https://user-images.githubusercontent.com/201608/137821197-50209b9b-3ef1-4278-86ec-989a4ac0beea.png" width=500>

The differences are entirely in the header:
```html
<div class='main main-body'>
    <div class='header container'>
      <div class='logo-container'>
        <a href="/"></a>
        <a class="logo-text" href="/">Indy Hackers</a>
      </div>
      <ul class='menu'>
        <li><a href="/newsletter">Newsletter</a></li>
        <li><a href="/jobs">Jobs</a></li>
        <li><a href="/about">About</a></li>
      </ul>
    </div>
    <div class='content clear-fix'>
```
```css
.container {
    max-width: 1280px;
    width: 100%;
    margin: 0 auto;
    padding: 2% 5%
}
/* ... ... */
.menu li {
    margin-right: 28px
}
```

becomes:
```html
  <div class='main main-body container'>
    <div class='header navbar'>
      <nav class='logo-container navleft'>
        <a href="/"></a>
        <a class="logo-text" href="/">Indy Hackers</a>
      </nav>
      <nav class='menu navright'>
        <a href="/newsletter" class="navright">Newsletter</a>
        <a href="/jobs" class="navright">Jobs</a>
        <a href="/about" class="navright">About</a>
      </nav>
    </div>
    <div class='content clear-fix'>
```
```css
.container {
    max-width: 1280px;
    /* width: 100%; */
    margin: 0 auto;
    padding: 2% 5%
}
/* ... ... */
.navbar {
  display: flex;
  flex-direction: row;
  align-items: center;
  width: 100%;
}
.navleft {
  flex-grow: 1;
}
/* ... ... */
.menu > a {
    margin-right: 28px
}
```

I realize this is a super annoying way to report this, but I am sure it's an easy fix. It's likely about 10 minutes worth of editing if you know how Ruby and all this works, but I wasn't able to get a dev env setup without lots of headaches so I gave up and just did it with dev tools. I also know it can be better, I think the container should still probably be 100% width, but it was a lot of extra troubleshooting to do manually when I am pretty sure that should be fairly obvious to someone with the right environment set up.

Let me know if you have any questions.
